services:
  reverse-proxy:
    image: traefik:v3.4
    container_name: traefik-reverse-proxy
    restart: unless-stopped
    command:
      - --log.level=info
      - --api=true
      - --api.dashboard=true
      - --api.debug=true
      - --api.insecure=true
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedbydefault=false
      - --certificatesresolvers.le.acme.dnschallenge=true
      - --certificatesresolvers.le.acme.dnschallenge.provider=digitalocean
      - --certificatesresolvers.le.acme.email=
      - --certificatesresolvers.le.acme.storage=/home/server_admin/traefik/config/acme.json
    environment:
      - DO_AUTH_TOKEN=
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/server_admin/traefik/config:/home/server_admin/traefik/config
    networks:
      - web

networks:
  web:
    external: true
